### ISSUE TITLE
Item in drop message isn't Title Cased consistently

### ISSUE THREAD

**Issue by ryanzwe** [tmein/frosty-discord-bot#2] opened 2024-06-10 00:10 UTC
Hello Mr.Developer

I have noticed that not all items are using Title Casing, this makes the product look budget.

<img width="402" alt="image" src="https://github.com/tmein/frosty-discord-bot/assets/10244230/a969c2a9-0486-451c-a7f3-dd0aa7d69a5f">

This has devalued Snakey's hard work and we would like compensation

**Comment by tmein** [comment] 2024-06-10 00:14
This is consistent with the RuneMetrics drop log message, the issue is upstream. Closing as not planned.
![image](https://github.com/tmein/frosty-discord-bot/assets/29010365/859335c5-dc9e-436b-b370-6ae4f8cec5d1)

**Closed as not planned** 2024-06-10 00:14 UTC

**Comment by ryanzwe** [comment] 2024-06-10 00:17
Just because the data upstream is bad doesn't mean this prouduct should be. Does this mean we can expect the Frosty Knights Official Discord Bot to be as bad as the RuneMetrics drop log instead of a more polished product!?
